#!/usr/bin/env bash
# comment
sudo apt update -y
sudo apt install haproxy -y
echo 'ENABLED=1' | sudo tee -a /etc/default/haproxy
printf %s 'backend web-backend
        balance roundrobin
        server 4803-web-01 54.175.103.141:80 check
        server 4803-web-02 184.72.64.31:80 check
frontend http
        bind *:80
        mode http
        default_backend web-backend
' | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
