#!/usr/bin/env bash
#connect nginx to port 80
sed -i "s/listen [::]:8080;/listen [::]:80;/" /etc/nginx/sites-enabled/default
sed -i "s/listen [::]:8080;/listen [::]:80;/" /etc/nginx/sites-available/default
service nginx restart
