#!/usr/bin/env bash
#Installing nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
sudo service nginx restart
