#!/usr/bin/env bash
#Installing nginx
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://onepiece.fandom.com/wiki/One_Piece_Wiki permanent;" /etc/nginx/sites-enabled/def
sudo service nginx restart
